# --- Setup

export ZSH="/home/spin/.oh-my-zsh"

ZSH_THEME="fino-time"
HIST_STAMPS="dd/mm/yyyy"

# --- Plugins

plugins=(
    git
    zsh-completions
    zsh-syntax-highlighting
    zsh-autosuggestions
    zsh-interactive-cd
)

# --- Oh My Zsh

source $ZSH/oh-my-zsh.sh

# --- User configuration

export MANPATH="/usr/local/man:$MANPATH"
export LANG=en_US.UTF-8

# === SPIN specific

# --- Include custom bin folder

if [[ $SPIN == '1' ]]
then
    export PATH=$HOME/.bin:$PATH
fi

# --- Extensions

if [[ $SPIN == '1' ]]
then
    source $HOME/.zsh/config/spin/aliases.zsh
fi

# --- Message Banner

if [[ $SPIN == '1' ]]
then
    cat $HOME/.zsh/banners/spin
fi